# Docker Compose Production Environments 
version : '3'
services:

        vote-api:
                build:
                        context: .
                        dockerfile: dockerfiles/flask/Dockerfile
                image: open-vote-api-services
                entrypoint: ./build.sh
                env_file: .env
                ports:
                - 5000:5000
                depends_on:
                - postgres
                restart: always
                networks:
                - traefik-net
                labels:
                - "traefik.frontend.rule=Host:vote-api.vousmeevoyez.xyz"

        postgres:
                build:
                        context: dockerfiles/postgresql/
                environment:
                - POSTGRES_USER=$DB_USERNAME
                - POSTGRES_PASSWORD=$DB_PASSWORD
                restart: always
                volumes:
                - "persist_volume:/var/lib/postgresql/data"
                networks:
                - traefik-net

        vote-grpc:
                image: open-vote-grpc
                entrypoint: ./start.sh
                env_file: .env
                ports:
                - 5001:5001
                depends_on:
                - vote-api
                restart: always
                networks:
                - traefik-net
                labels:
                - "traefik.frontend.rule=Host:vote-grpc.vousmeevoyez.xyz"

volumes:
        persist_volume:

networks:
        traefik-net:
                external: true
