# Docker Compose Production Environments 
version : '3'
services:

        flask:
                image: open-vote-api-services
                entrypoint: ./build.sh
                environment:
                - DB_USERNAME=$DB_USERNAME
                - DB_PASSWORD=$DB_PASSWORD
                - DB_HOSTNAME=$DB_HOSTNAME
                - DB_NAME=$DB_NAME
                - ENVIRONMENT=$ENVIRONMENT
                - HOST=$HOST
                ports:
                - 5000:5000
                depends_on:
                - postgres
                restart: always
                networks:
                        app_net:
                                ipv4_address: 172.16.238.10

        postgres:
                build:
                        context: dockerfiles/postgresql/
                environment:
                - POSTGRES_USER=$DB_USERNAME
                - POSTGRES_PASSWORD=$DB_PASSWORD
                restart: always
                networks:
                        app_net:
                                ipv4_address: 172.16.238.12

        grpc:
                image: open-vote-grpc
                entrypoint: ./start.sh
                environment:
                - GRPC_ENDPOINT_URL=$GRPC_ENDPOINT_URL
                - GRPC_PORT=$GRPC_PORT
                restart: always
                ports:
                - 5001:5001
                depends_on:
                - flask
                networks:
                        app_net:
                                ipv4_address: 172.16.238.14

networks:
        app_net:
                driver: bridge
                ipam:
                        driver: default
                        config:
                        - subnet: 172.16.238.0/24

