"""added blacklist token

Revision ID: 036631130441
Revises: e854ed68756a
Create Date: 2019-03-07 16:31:45.376950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036631130441'
down_revision = 'e854ed68756a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'candidate', ['id'])
    op.create_unique_constraint(None, 'election', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'vote', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'election', type_='unique')
    op.drop_constraint(None, 'candidate', type_='unique')
    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
